### ISSUE TITLE
use vue-cli 3.0 way when it's ready

### ISSUE THREAD

**Issue by DrSensor** [DrSensor/vue-authoring-template#2]
This issue for anticipating [`vue-cli 3.0`](https://github.com/vuejs/vue-cli/issues/589).

Currently, this template using `poi` because `vue build` was removed. `Poi` is great for scaffolding project and hide the configuration project in prebuilt `poi-presets`. However, it's also not really *copas* friendly because it uses [`webpack-chain`](https://github.com/mozilla-neutrino/webpack-chain) format for extending webpack configuration while many `webpack-loader` and `storybook-addon` in their __README__ use curly brackets format and that make some user confused how to add that addon/loader. To make it *copy-paste* friendly, need to introduce `config.merge(curlyBracketConfig)` in the `.storybook/poi.config.js`. 

Take for example [`storybook-readme`](https://github.com/tuchk4/storybook-readme#webpack-configuration-for-vue-storybook), if this template use [webpack config of storybook](https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode) then the user will know where to put `storybookBaseConfig` to apply that addon.

> need to keep on track `poi-preset-storybook` with storybook default config. Create `commit change bot` maybe...

**Comment by egoist** [comment]
Well we can add `markdown-loader` to the storybook preset if that's supported by storybook.

btw `vue-cli` 3.0 uses webpack-chain too.

**Comment by DrSensor** [comment]
Interesting. Is there any benefit using webpack-chain? I find it hard using webpack-chain because many webpack config example use curly-bracket format.

**Comment by egoist** [comment]
This introduction explains it pretty well https://github.com/mozilla-neutrino/webpack-chain#introduction

**Comment by DrSensor** [comment]
Switch to #15
